name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Greetings to PnS-Connect. Don't forget to star the repo!!!"
        pr-message: "Thank you for contributing to the repo. Don't forget to star the repo!!!"
